### PR TITLE
fix: block and transaction confirmations

### LINKED ISSUE #575: Buggy confirmation count on the transaction and block pages
**Describe the bug**
The confirmation count on the transaction and block pages behaves funky. Will be fixed by eod.

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Fixes #575.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by ghost** [comment]
@dated Thanks for submitting this pull request, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@alexbarnsley @faustbrian @luciorubeens - please review this in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
@j-a-m-l The [ci/circleci: test-node-10](https://circleci.com/gh/dated/ark-explorer/964?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [7fa01163f45b21eed6aa6162c0ff2a5842f1fb73](https://github.com/ArkEcosystem/explorer/commit/7fa01163f45b21eed6aa6162c0ff2a5842f1fb73). Please [review the logs for more information](https://circleci.com/gh/dated/ark-explorer/964?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Review by j-a-m-l — CHANGES_REQUESTED** [review]
I'm receiving a `Network Error` when loading or reloading the transaction page, but the request is successful and contains the transaction data.

Apart from this, could you elaborate about what do you consider a "funky" behaviour? On the block page I didn't see any difference with the current version.

**Comment by ghost** [comment]
@dated Your pull request needs some changes. Please wait for a comment from one of our developers for more information.

**Comment by dated** [comment]
I'll check that `Network Error`. The block details would sometimes show a negative value, I think I couldn't reproduce that with the confirmations as computed property. I'll test that again also.

**Comment by j-a-m-l** [comment]
@dated I didn't saw any problem with the confirmations on the block page, that's why I needed more info about what was "funky".

**Comment by dated** [comment]
Hmm, I'm unable to reproduce the `Network Error`, do you have more details on that?

**Comment by j-a-m-l** [comment]
The error is thrown on `fetchTransaction`, on `src/pages/Transaction.vue` due CORS when requesting data to `min-api.cryptocompare.com`.

How do you try the app locally? (I'm using `yarn dev:<network>`)

**Comment by dated** [comment]
That method doesn't get called when a transaction is found, and even when the transaction can't be found and the method is called by pressing the `Reload` button I can't reproduce the error, neither on Main- nor Devnet 🤔 

I start the explorer the same way.

File: src/pages/Transaction.vue [hunk 1]
```diff
@@ -108,11 +108,23 @@ export default {
...
   },
 
-  async mounted() {
-    await this.prepareComponent()
+  watch: {
+    async currencySymbol() {
+      await this.updateAverage()
+    },
+
+    height() {
```
Comment (j-a-m-l) [inline src/pages/Transaction.vue:123]: Maybe `initialBlockWeight` could be refactored to a computed property.

**Comment by j-a-m-l** [comment]
Yes, that's method is called when clicking on "Reload". In this case the problem was my browser that was blocking those requests, when calling `CryptoCompareService.dailyAverage` on that method and other places, such as the `beforeRouteEnter` hook.

File: src/pages/Transaction.vue (hunk 1 above)
Comment (dated) [reply src/pages/Transaction.vue:123]: I don't see a way for that, since `initialBlockHeight` depends on the current network height but needs to stay static.

Comment (j-a-m-l) [reply src/pages/Transaction.vue:123]: Yes, I'm going to refactor this on a new PR.

**Review by j-a-m-l — APPROVED** [review]
Good work @dated

**Comment by ghost** [comment]
@dated A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
@dated Your pull request has been merged but was not assigned a bounty tier. @alexbarnsley @faustbrian @luciorubeens - please assign a bounty tier to this pull request in the next few days.

**Comment by ghost** [comment]
@dated Your pull request has been merged and marked as tier 4. _It will earn you $10 USD._

**Comment by ItsANameToo** [comment]
closing in favour of #562
