### PR TITLE
fix: break long delegate names

### LINKED ISSUE #631: bug: smartbridge width
#626 introduced truncating the smartbridge field, but as a side effect it sets a specified `max-width` which can result in the table going out of bounds when a vote/unvote tx is listed that contains a long delegate name (see how the right side of the table extends over the black background):

image

### PR DESCRIPTION
**Pull request by ItsANameToo**
Resolves #631 by breaking up long delegate names 

## What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

File: tests/Unit/Services/Monitor/MissedBlockCalculatorTest.php [hunk 1]
```diff
@@ -70,62 +70,62 @@
...
-        '0250b742256f9321bd7d46f3ed9769b215a7c2fb02be951acf43bc51eb57ceadf6',
-        '02c3d1ae1b8fe831218f78cf09d864e60818ebdba4aacc74ecc2bcf2734aadf5ea',
-        '02951227bb3bc5309aeb96460dbdf945746012810bb4020f35c20feae4eea7e5d4',
-        '022eedf9f1cdae0cfaae635fe415b6a8f1912bc89bc3880ec41135d62cbbebd3d3',
-        '0306950dae7158103814e3828b1ab97a87dbb3680db1b4c6998b8208865b2f9db7',
-        '02aabcdb8511f55b6a28593979b726ef55b1f5bbf16a83205c2e2bfc9d8c2909e3',
-        '03a8ff0a3cbdcb3bfbdb84dbf83226f338ba1452047ac5b8228a1513f7f1de80de',
         '03f08761f99892996c6771761955ec41ee6cdffadd43171228f5f28f8c76423b3d',
-        '02ff842d25fc8eec9e1382e6468188b3fd130ab6246240fc97958ce83d6d147eaf',
+        '02e345079aca0567db96ec0ba3acf859b7cfd15134a855671f9c0fe8b1173767bd',
```
Comment (ItsANameToo) [inline tests/Unit/Services/Monitor/MissedBlockCalculatorTest.php:74]: why the order change? :trollface: was the initial list wrong or did you make it match whatever the test outputs?

**Comment by ItsANameToo** [comment]
@air1one there is a different test failing, because of your change to the calculation of the next round number

File: tests/Unit/Services/Monitor/MissedBlockCalculatorTest.php (hunk 1 above)
Comment (air1one) [reply tests/Unit/Services/Monitor/MissedBlockCalculatorTest.php:74]: yeah the issue was in the test not in the code :trollface: the order I pushed initially was not taking into account the shuffling based on slot

File: app/Services/Monitor/MissedBlocksCalculator.php [hunk 2]
```diff
@@ -22,13 +22,13 @@ public static function calculateForLastXDays(int $height, int $numberOfDays): ar
             ->firstOrFail()->height->toNumber();
         $forgingStats = [];
         for ($h = $startHeight; $h <= $height; $h += Network::delegateCount()) {
-            $forgingStats = self::calculateForRound($h, $forgingStats);
+            $forgingStats = $forgingStats + self::calculateForRound($h);
```
Comment (faustbrian) [inline app/Services/Monitor/MissedBlocksCalculator.php:24]: Is `+` what we want to use in this case? https://stitcher.io/blog/array-merge-vs+

Comment (air1one) [reply app/Services/Monitor/MissedBlocksCalculator.php:24]: yes there should be no overlap between current `$forgingStats` and the next calculated, I used `+` to preserve the timestamp as key (otherwise `array_merge` would replace the timestamp keys with regular zero-based index)

File: app/Console/Commands/BuildForgingStats.php [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+
+    /**
+     * Execute the console command.
+     *
+     * @return int
+     */
+    public function handle()
+    {
+        $height = intval($this->option('height'));
+        $days   = floatval($this->option('days'));
```
Comment (ItsANameToo) [inline app/Console/Commands/BuildForgingStats.php:34]: why `floatval`? partial days? 🤔

File: app/Services/Monitor/MissedBlocksCalculator.php [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+
+use App\Models\Round;
+use App\Services\Monitor\Actions\ShuffleDelegates;
+
+final class MissedBlocksCalculator
+{
+    public static function calculateForLastXDays(int $height, float $numberOfDays): array
+    {
+        $heightTimestamp     = Block::where('height', $height)->firstOrFail()->timestamp;
+        echo 'height ts : '.$heightTimestamp;
```
Comment (ItsANameToo) [inline app/Services/Monitor/MissedBlocksCalculator.php]: please remove the `echo` statements

File: tests/migrations/2021_03_11_000000_create_forging_stats_table.php [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+            $table->boolean('forged');
+            $table->timestamp('created_at')->nullable();
+            $table->timestamp('updated_at')->nullable();
+        });
+    }
+
+    public function down()
+    {
+        Schema::dropIfExists('forging_stats');
+    }
```
Comment (ItsANameToo) [inline tests/migrations/2021_03_11_000000_create_forging_stats_table.php:25]: you can remove the `down` method, we don't do rollbacks and if we need it we add a new migration instead

File: app/Services/Monitor/MissedBlocksCalculator.php [hunk 6]
```diff
@@ -0,0 +1,77 @@
...
+            ->toArray();
+
+        $firstBlockInRoundTheoricalTimestamp = $lastRoundLastBlockTs + Network::blockTime();
+        $slotNumberForFirstTheoricalBlock    = (new Slots())->getSlotInfo($firstBlockInRoundTheoricalTimestamp)['slotNumber'];
+        $finalDelegateOrderForRound          = array_merge(
+            array_slice($tempDelegateOrderForTheRound, $slotNumberForFirstTheoricalBlock % $activeDelegates),
+            array_slice($tempDelegateOrderForTheRound, 0, $slotNumberForFirstTheoricalBlock % $activeDelegates)
+        );
+
+        $theoricalBlocksByTimestamp = [];
```
Comment (ItsANameToo) [inline app/Services/Monitor/MissedBlocksCalculator.php]: `theorical` = `theoretical`? :trollface:

File: app/Services/Monitor/MissedBlocksCalculator.php [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+        $forgingStats = [];
+        echo 'start height: '.$startHeight.' ; end height : '.$height;
+        for ($h = $startHeight; $h <= $height; $h += Network::delegateCount()) {
+            $forgingStats = $forgingStats + self::calculateForRound($h);
+        }
+
+        return $forgingStats;
+    }
+
+    public static function calculateForRound(int $height): array
```
Comment (ItsANameToo) [inline app/Services/Monitor/MissedBlocksCalculator.php:30]: can this be split up into multiple smaller methods? e.g. something like:
- calculateBlockTimestamps
- calculateDelegateOrder
- calculateTheoreticalBlocks
- calculateForgeInfo

to make it more clear what is done exactly as it's a lot of assignments and calculations at the moment
